apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-frontend
  namespace: dynamic-ads
  labels:
    app: es-frontend
spec:
  selector:
    matchLabels:
      tier: es-frontend
  replicas: 1
  template:
    metadata:
      name: es-frontend
      labels:
        tier: es-frontend
    spec:
      containers:
        - name: es-frontend
          image: 165463520094.dkr.ecr.ap-northeast-1.amazonaws.com/dynamic-ads/kv-store-proxy-gateway:1.0.50
          ports:
            - containerPort: 8080
              name: port